title: Video to GIF
email: videotogif2025@example.com
description: >-
  Convert videos to high-quality GIFs directly in your browser.
baseurl: ""
url: "https://videotogif.github.io"
github_username: videotogif

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
